connections:
  listener:
    host: "0.0.0.0"
    port: "8082"
    basepath: "/api/*"
  sys_user_api:
    host: "0.0.0.0"
    port: "8081"
    basepath: "/api"
    path:
      get-user: "/users/{username}"
      get-users: "/users"
      post-create-user: "/users"
    