connections:
  listener:
    host: "0.0.0.0"
    port: "8081"
    basepath: "/api/*"
  mysql:
    host: "localhost"
    port: "3306"
    db: "mydb"
    
os:
  maxentries: "1"
  ttl: "30"
  interval: "1"
